#!/bin/bash

# COLORS {{{
Bold=$(tput bold)
Underline=$(tput sgr 0 1)
Reset=$(tput sgr0)
# Regular Colors
Red=$(tput setaf 1)
Green=$(tput setaf 2)
Yellow=$(tput setaf 3)
Blue=$(tput setaf 4)
Purple=$(tput setaf 5)
Cyan=$(tput setaf 6)
White=$(tput setaf 7)
# Bold
BRed=${Bold}$(tput setaf 1)
BGreen=${Bold}$(tput setaf 2)
BYellow=${Bold}$(tput setaf 3)
BBlue=${Bold}$(tput setaf 4)
BPurple=${Bold}$(tput setaf 5)
BCyan=${Bold}$(tput setaf 6)
BWhite=${Bold}$(tput setaf 7)
#}}}

print_line() {
  printf "%$(tput cols)s\n"|tr ' ' '*'
}


print_title() {
  clear
 print_line
  echo -e "# ${Bold}$1${Reset}"
  print_line
  echo ""
}

  x_="______________________________________________________________________________"

print_title "${BGreen}Install FireBox Start\n"



echo ""
echo "${BWhite} ################################################################## "
echo " ############################################################################ "
echo " ADAMS AWESOME HACK_ "

echo "  "
echo ""
echo ${White}$x_
echo ""
echo "${BBlue}[+][INFO]:: Install FireBox Start "
echo "${White}"

